
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "installing sam"
      - pip install --upgrade pip
      - pip install aws-sam-cli
  pre_build:
    commands:
      - echo "installing npm packages "
      - cd hello-world && npm install
      - echo "running unit test "
      - npm run test && cd ..

  build:
    commands:
      - echo build started at `date` for environment $ENV_NAME
      - export SAM_CLI_TELEMETRY=0 
      - sam package --s3-bucket chat-gateway-bucks-$ENV_NAME --template-file template.yaml --output-template-file payment-gateway-package.yaml
      - echo "deploying"
      - sam deploy --template-file payment-gateway-package.yaml --stack-name payment-gateway-$ENV_NAME --capabilities CAPABILITY_IAM
  post_build:
    commands:
      - echo deployment completed at `date`